# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Enable corepack to use bundled pnpm
RUN corepack enable

COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

# Production stage: Nginx to serve static files
FROM nginx:alpine

# Copy custom nginx config (forces 2 workers)
COPY nginx.conf /etc/nginx/nginx.conf

# Copy exported static site output generated by Vite
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
